# Generated by Django 4.2.7 on 2025-11-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "original_url",
                    models.URLField(
                        help_text="URL completa que sera encurtada",
                        max_length=2048,
                        verbose_name="URL Original",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        help_text="Codigo unico para a URL encurtada",
                        max_length=10,
                        unique=True,
                        verbose_name="Codigo Curto",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Define se o link esta ativo", verbose_name="Ativo"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de expiracao do link",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "max_clicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero maximo de cliques unicos permitidos",
                        verbose_name="Maximo de Cliques unicos",
                    ),
                ),
                (
                    "total_clicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Contador total de cliques",
                        verbose_name="Total de Cliques",
                    ),
                ),
                (
                    "unique_clicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Contador de cliques unicos (baseadoem IP)",
                        verbose_name="Cliques Unicos",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem do QR Code gerado automaticamente",
                        null=True,
                        upload_to="qrcodes/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criacao", verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data da utlima atualizacao",
                        verbose_name="Atualizado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL Encurtada",
                "verbose_name_plural": "URLs Encurtadas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["short_code"], name="shortener_s_short_c_f1ca7f_idx"),
                    models.Index(fields=["created_at"], name="shortener_s_created_5011aa_idx"),
                    models.Index(fields=["is_active"], name="shortener_s_is_acti_2350ee_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP do usuario que clicou", verbose_name="Endereco IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Navegador e sistema operacional",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "referer",
                    models.URLField(
                        blank=True,
                        help_text="URL de onde veio o clique",
                        max_length=2048,
                        null=True,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora do clique",
                        verbose_name="Clicando em",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        help_text="URL encurtada que foi clicada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Clicks",
                        to="shortener.shortenedurl",
                        verbose_name="URL",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Clique",),
                "verbose_name_plural": "Cliques",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["url", "ip_address"], name="shortener_c_url_id_f84180_idx"
                    ),
                    models.Index(fields=["clicked_at"], name="shortener_c_clicked_5992aa_idx"),
                    models.Index(
                        fields=["url", "clicked_at"], name="shortener_c_url_id_ba2c7f_idx"
                    ),
                ],
            },
        ),
    ]
