# Generated by Django 4.2.7 on 2025-11-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="url",
            field=models.ForeignKey(
                help_text="URL encurtada que foi clicada",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="shortener.shortenedurl",
                verbose_name="URL",
            ),
        ),
    ]
